#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIBdjV8xoib5i0CDT8oPHGEa2ZoNpJCey+PsdAW1mMwUfVEwLK/mF/fXY+s9vBFmIJWdaoWYH0zHlxgOG5FTyU6DuiJ9FpzdAQIOPZaEagj0W92KV+i0mkFseHdik6274jYcBOXfG497s/VjYSe3C/TsDZTXeMLhZxJT0fwbwfwu9tSmwEX/t2nMLaNz54z8VQbs1L1M/EeG+jARbYhLG+CjrIzU07ouaUBMsCK2cttNG4O/pbUCUkRm8iavwEBb4sOPGMD1DeO70T1zSe+f1ZaKlrZpJimI+BhMOBQSJHtTD0BaXiuXLdJNHJnRpgDeflTtbtxtX0z/Y+x3jaGByr
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD PublicKey_Nussle
ssh_pwauth: false
disable_root: false

package_update: true
packages:
  - curl 
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer

write_files:
  - path: /var/www/html/info.php
    content: |
      <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      ?>
  - path: /var/www/html/db.php
    content: |
      <html>
      <head></head>
      <body>
      Diese Seite macht eine Abfrage auf die Datenbank. <br />
      Das ausgeführte Query ist: <i>select Host, User from mysql.user;</i><br /><br />
      Das Resultat: <br />
      <?php
              //database
              $servername = "54.234.19.229"; 
              $username = "admin";
              $password = "SicheresPasswort"; # Bitte das tatsächliche Passwort eintragen
              $dbname = "mysql";

              // Create connection
              $conn = new mysqli($servername, $username, $password, $dbname);
              // Check connection
              if ($conn->connect_error) {
                      die("Connection failed: " . $conn->connect_error);
              }

              $sql = "select Host, User from mysql.user;";
              $result = $conn->query($sql);
              while($row = $result->fetch_assoc()){
                      echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
              }
      ?>
      </body>
      </html>

runcmd:
  - sudo systemctl start apache2
  - sudo systemctl enable apache2
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
